version: '3.7'
services:
  nginx:
   container_name: jh_nginx
   image: nginx:1.13
   restart: always
   ports:
   - 80:80
   volumes:
   - ./nginx/conf.d:/etc/nginx/conf.d
   - ./nginx/logs:/var/log/nginx/
   depends_on:
   - app

  app:
    restart: always
    build: ./app
    #working_dir: ./app
    #volumes:
    #  - ./app:/app
    expose:
      - "8080"
    command: java -jar app/spring-boot-sample-web-ui-0.0.0.jar
