FROM java:8
MAINTAINER jaebung <jaehoon-yoo@nhnent.com>

COPY ./src/spring-boot-sample-web-ui-0.0.0.jar /app/spring-boot-sample-web-ui-0.0.0.jar
EXPOSE 8080

CMD ["java -jar app/spring-boot-sample-web-ui-0.0.0.jar"]
